### ISSUE TITLE
unable to run Run.sh

### ISSUE THREAD

**Issue by dvitrano** [Doodle3D/openwrt-buildroot-example#13] opened 2015-07-20 12:55 UTC
Hi there maybe something very stupid on my side however when I try to run the Run.sh I get the following error:
/openwrt-buildroot-example$ sh ./Run.sh interactive
./Run.sh: 18: ./Run.sh: Syntax error: "(" unexpected

any hint?

**Comment by peteruithoven** [comment] 2015-07-20 15:25
I've tried reproducing this, but couldn't. 
I also tried this after removing my existing interactive-buildroot. 
What platform are you running this from (linux / OS X / ...)? 
It seems to break on the first occorance of a function (`function clone() {`), maybe there is a difference between my `sh` en your `sh?`. I'll admit we've mostly tested this on OS X. 

In the version we use we changed the first line (of Run.sh) to use bash, to increase Linux support, could you try that? 

```
#!/bin/bash
```

Since we haven't found a nice way to extend this example with our (private) customizations it's hard to keep them in sync.

**Comment by dvitrano** [comment] 2015-07-20 17:09
Thanks Peter!
I'm trying under Ubuntu Server.
I git-cloned the repo into OS X and I can confirm the script works.
not sure how to test the bash thing since uncommenting it does produce a file not found error.
will keep on trying..

**Comment by peteruithoven** [comment] 2015-07-20 19:40
I'll try this on Ubuntu myself. In the mean time, what I meant was changing the first line of Run.sh from:

```
#!/bin/sh
```

to: 

```
#!/bin/bash
```

**Comment by peteruithoven** [comment] 2015-07-20 20:10
I could replicate your issue using the Ubuntu image used in Docker. Basically this is the incompatibility between bash and sh. See: http://stackoverflow.com/questions/5725296/difference-between-sh-and-bash/5725402#5725402
Apparently we're doing bash specific stuff. 
Changing the line to `#!/bin/bash` and executing it without specifying with what, seems to work:

```
./Run.sh
```

You can also explicitly run it as bash, but that seems unusual.:

```
bash ./Run.sh
```

**Comment by peteruithoven** [comment] 2015-07-20 20:15
I've opened a new issue on switching to sh: https://github.com/Doodle3D/openwrt-buildroot-example/issues/14

**Comment by peteruithoven** [comment] 2015-07-20 20:19
You can also do a `git pull` now and run:

```
./Run.sh
```

Please let me know if the issue persists, I'm closing the issue for now.

**Closed as completed by peteruithoven** 2015-07-20 20:19 UTC
